name: TF Backend State Provisioning

on:
  workflow_dispatch:

jobs:
  InfraProvision:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./tf_backend_state
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.2

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -var-file="prod.tfvars" -out terraform.tfplan

      - name: Provision backend state
        run: terraform apply -auto-approve terraform.tfplan